# Clave única del proyecto en SonarCloud
sonar.projectKey=FMAT-Restaurant_Auth-Frontend
sonar.organization=fmat-restaurant

# Nombre descriptivo
sonar.projectName=Auth-Frontend
sonar.projectVersion=1.0

# Rutas de código fuente y pruebas
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.tsx,src/**/*.test.ts
sonar.exclusions=src/**/*.test.tsx,src/**/*.test.ts,dist/**,node_modules/**,coverage/**

# Configuración de JavaScript/TypeScript y Cobertura (LCOV)
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true
